/**
 * Source of the pi extension that bridges pi's tool system to DevTerm's
 * in-process MCP server. Written to a per-session temp directory by
 * prepareAgentLaunch() and loaded by pi with `-e <path>`.
 *
 * pi loads extensions via jiti, so this file can use TypeScript syntax even
 * though we do not transpile it ourselves. The extension is fully
 * self-contained: it uses Node 18+ built-in `fetch` for the streamable-HTTP
 * MCP transport and a small inline `Type` shim that produces typebox-shaped
 * objects for tool parameter schemas (pi's `registerTool` accepts any object
 * whose `.static` field is a JSON schema).
 *
 * Bridge URL, bearer token, and overlay dir are passed in via env vars so we
 * never serialize secrets into the file on disk. The MCP session id is
 * persisted under `DEVTERM_MCP_DIR` (the per-session overlay — not the
 * operator's project cwd) so the extension can rejoin after pi's `/reload`;
 * the bridge rejects a second `initialize` with 400 "Server already initialized".
 */

export const PI_EXTENSION_SOURCE = String.raw`// DevTerm MCP bridge extension for the pi coding agent.
// DO NOT EDIT THIS FILE BY HAND — it is generated from src/main/agent/extension.ts.

import { readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

const BRIDGE_URL = process.env.DEVTERM_BRIDGE_URL
const BRIDGE_TOKEN = process.env.DEVTERM_BRIDGE_TOKEN
// Overlay dir (not the operator's project). Native local agents spawn with
// cwd = the project, so the MCP session file must not land in the repo.
const MCP_DIR = process.env.DEVTERM_MCP_DIR || process.cwd()
const MODEL_FALLBACKS = (() => {
  try {
    const parsed = JSON.parse(process.env.DEVTERM_MODEL_FALLBACKS || '[]')
    return Array.isArray(parsed) ? parsed.filter((v) => typeof v === 'string' && v.includes('/')) : []
  } catch {
    return []
  }
})()

if (!BRIDGE_URL || !BRIDGE_TOKEN) {
  throw new Error('DevTerm MCP bridge env vars not set (DEVTERM_BRIDGE_URL / DEVTERM_BRIDGE_TOKEN)')
}

// Persisted in DEVTERM_MCP_DIR (the per-session overlay) so the MCP session
// id survives a pi \`/reload\`. Native local agents use the project as cwd, so
// this must not be process.cwd(). The bridge rejects a second \`initialize\`
// with 400 once it's up; the only way to keep working after a reload is to
// rejoin the existing session with its id.
const SESSION_FILE = join(MCP_DIR, 'devterm-mcp-session.json')

function loadSessionId() {
  try {
    const data = readFileSync(SESSION_FILE, 'utf8')
    const obj = JSON.parse(data)
    return typeof obj.sessionId === 'string' && obj.sessionId ? obj.sessionId : null
  } catch {
    return null
  }
}

function saveSessionId(sessionId) {
  try {
    writeFileSync(SESSION_FILE, JSON.stringify({ sessionId }))
  } catch {
    /* best-effort; a future reload will just re-handshake */
  }
}

// Minimal typebox-compatible schema constructors. pi's tool runtime reads the
// \`static\` field of the parameter schema and passes it to typebox's Value.Check
// for validation. Constructing plain objects with the right \`static\` shape
// is sufficient — we don't need the real typebox package.
function jsonSchemaToTypebox(schema) {
  if (!schema || typeof schema !== 'object') return { static: {} }
  if (schema.type === 'object' || schema.properties) {
    const properties = {}
    for (const [key, value] of Object.entries(schema.properties || {})) {
      properties[key] = jsonSchemaToTypebox(value)
    }
    const static_ = {
      type: 'object',
      properties: Object.fromEntries(
        Object.entries(properties).map(([k, v]) => [k, v.static])
      )
    }
    if (Array.isArray(schema.required) && schema.required.length > 0) {
      static_.required = schema.required
    }
    return { static: static_ }
  }
  if (schema.type === 'array') {
    return { static: { type: 'array', items: jsonSchemaToTypebox(schema.items || {}).static } }
  }
  if (schema.type === 'string') {
    return { static: { type: 'string', ...(schema.description ? { description: schema.description } : {}) } }
  }
  if (schema.type === 'number') {
    return { static: { type: 'number', ...(schema.description ? { description: schema.description } : {}) } }
  }
  if (schema.type === 'integer') {
    return { static: { type: 'integer', ...(schema.description ? { description: schema.description } : {}) } }
  }
  if (schema.type === 'boolean') {
    return { static: { type: 'boolean', ...(schema.description ? { description: schema.description } : {}) } }
  }
  return { static: {} }
}

let requestId = 1

async function mcpCall(method, params, sessionIdRef) {
  const headers = {
    'Content-Type': 'application/json',
    'Accept': 'application/json, text/event-stream',
    'Authorization': 'Bearer ' + BRIDGE_TOKEN
  }
  if (sessionIdRef.value) headers['Mcp-Session-Id'] = sessionIdRef.value
  const isNotification = method.startsWith('notifications/')
  const body = isNotification
    ? JSON.stringify({ jsonrpc: '2.0', method, params })
    : JSON.stringify({ jsonrpc: '2.0', id: requestId++, method, params })
  const resp = await fetch(BRIDGE_URL, { method: 'POST', headers, body })
  const newSessionId = resp.headers.get('mcp-session-id')
  if (newSessionId) sessionIdRef.value = newSessionId
  if (!resp.ok) {
    const text = await resp.text().catch(() => '')
    throw new Error('MCP ' + method + ' failed: ' + resp.status + ' ' + text)
  }
  if (isNotification) return null
  const json = await resp.json()
  if (json.error) {
    const msg = json.error.message || ('code ' + json.error.code)
    throw new Error('MCP error: ' + msg)
  }
  return json.result
}

function registerMcpTools(pi, tools, sessionIdRef) {
  const names = new Set((tools || []).map((t) => t && t.name).filter(Boolean))
  // Browser tools first so they sit at the top of the model's tool list.
  const list = (tools || []).slice().sort(function (a, b) {
    var ab = String((a && a.name) || '').indexOf('browser_') === 0 ? 0 : 1
    var bb = String((b && b.name) || '').indexOf('browser_') === 0 ? 0 : 1
    return ab - bb
  })
  for (const tool of list) {
    const piName = 'mcp__devterm__' + tool.name
    const parameters = jsonSchemaToTypebox(tool.inputSchema)
    const description = tool.description || ('DevTerm MCP tool: ' + tool.name)
    const isBrowser = String(tool.name || '').indexOf('browser_') === 0
    // Pi only lists custom tools in the default "Available tools" prompt
    // section when promptSnippet is set. Without it the model discovers
    // browser_* late (or never) and reaches for bash/start instead.
    const promptSnippet = isBrowser
      ? (tool.name + ' — FIRST-CLASS DevTerm in-app browser. Never the OS browser.')
      : (tool.name + ' — DevTerm host MCP tool.')
    const promptGuidelines = tool.name === 'browser_open'
      ? [
          'Any URL or web UI: call mcp__devterm__browser_open (in-app pane). Never bash, start, xdg-open, or open.',
          'After open/navigate, mcp__devterm__browser_snapshot, then click/type by snapshot ref.'
        ]
      : undefined

    pi.registerTool({
      name: piName,
      label: isBrowser ? ('Browser · ' + tool.name.replace(/^browser_/, '')) : tool.name,
      description: isBrowser
        ? (description + ' This is a first-class DevTerm in-app browser tool; do not use the OS browser.')
        : description,
      promptSnippet: promptSnippet,
      promptGuidelines: promptGuidelines,
      parameters,
      async execute(_toolCallId, params) {
        const result = await mcpCall('tools/call', { name: tool.name, arguments: params || {} }, sessionIdRef)
        // The bridge returns { content: ContentBlock[], isError?: boolean };
        // pi's execute() returns the same shape, so we hand it back as-is.
        if (!result || !Array.isArray(result.content)) {
          return { content: [{ type: 'text', text: '(empty MCP result)' }] }
        }
        return result
      }
    })
  }

  // Remote: \`!command\` goes through MCP run_command on the SSH host.
  // Local native: that host tool is not registered — leave built-in bash alone
  // so \`!\` still runs on this machine.
  if (!names.has('run_command')) return
  pi.on('user_bash', async (event) => {
    if (!event || typeof event.command !== 'string') return
    return {
      result: await (async () => {
        const r = await mcpCall('tools/call', {
          name: 'run_command',
          arguments: { command: event.command }
        }, sessionIdRef)
        const text = (r?.content || [])
          .filter((b) => b && b.type === 'text' && typeof b.text === 'string')
          .map((b) => b.text)
          .join('')
        return {
          output: text,
          exitCode: r?.isError ? 1 : 0,
          cancelled: false,
          truncated: false
        }
      })()
    }
  })
}

function registerModelFailover(pi) {
  let nextFallback = 0
  let switching = false
  // After all fallbacks are exhausted, allow another pass once this cooldown
  // elapses (rate limits reset; a stuck session should not stay on the last
  // fallback forever).
  const FALLBACK_COOLDOWN_MS = 5 * 60 * 1000
  let exhaustedAt = 0
  pi.on('after_provider_response', async (event, ctx) => {
    const ok =
      typeof event.status === 'number' && event.status >= 200 && event.status < 300
    if (ok) {
      // A successful response means the current model is healthy again — reset
      // the cursor so a later rate-limit can walk the list from the top.
      nextFallback = 0
      exhaustedAt = 0
      return
    }
    if (switching || !(event.status === 408 || event.status === 429 || event.status >= 500)) return
    if (nextFallback >= MODEL_FALLBACKS.length) {
      if (exhaustedAt && Date.now() - exhaustedAt < FALLBACK_COOLDOWN_MS) return
      nextFallback = 0
      exhaustedAt = 0
    }
    switching = true
    try {
      while (nextFallback < MODEL_FALLBACKS.length) {
        const candidate = MODEL_FALLBACKS[nextFallback++]
        const slash = candidate.indexOf('/')
        const provider = candidate.slice(0, slash)
        const modelId = candidate.slice(slash + 1)
        if (!provider || !modelId) continue
        if (ctx.model?.provider === provider && ctx.model?.id === modelId) continue
        const model = ctx.modelRegistry.find(provider, modelId)
        if (!model || !ctx.modelRegistry.hasConfiguredAuth(model)) continue
        if (await pi.setModel(model)) {
          ctx.ui.notify(
            'Provider returned HTTP ' + event.status + '; switched the next request to ' + candidate,
            'warning'
          )
          return
        }
      }
      exhaustedAt = Date.now()
    } finally {
      switching = false
    }
  })
}

export default async function (pi) {
  // sessionIdRef lets the mcpCall closure read and update the session id
  // across calls; the value is also persisted to SESSION_FILE so that a
  // pi \`/reload\` (which re-imports this file as a fresh module) can pick
  // it back up and rejoin the bridge's live session.
  const sessionIdRef = { value: loadSessionId() }
  registerModelFailover(pi)

  if (sessionIdRef.value) {
    // Probe the persisted session with a cheap, idempotent call. If the
    // bridge still has it (the common case after /reload), we skip the
    // \`initialize\` handshake entirely — that's the call the server rejects
    // with 400 once it's already up. If the bridge was restarted and the
    // session is gone, the call fails and we fall through to a fresh
    // handshake below.
    try {
      const result = await mcpCall('tools/list', {}, sessionIdRef)
      if (result && Array.isArray(result.tools)) {
        registerMcpTools(pi, result.tools, sessionIdRef)
        return
      }
    } catch {
      sessionIdRef.value = null
    }
  }

  // First load, or the persisted session is no longer valid.
  await mcpCall('initialize', {
    protocolVersion: '2025-03-26',
    capabilities: {},
    clientInfo: { name: 'devterm-pi-extension', version: '1.0.0' }
  }, sessionIdRef)
  saveSessionId(sessionIdRef.value)
  await mcpCall('notifications/initialized', {}, sessionIdRef)

  const { tools } = await mcpCall('tools/list', {}, sessionIdRef)
  registerMcpTools(pi, tools, sessionIdRef)
}
`
